VERSION="2.0.0"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
  "GB4E45WIBUGCFXL6TTAOZU5L2FGH4VIM3KD2PYMPKAQN45QPBLBQZBCZ"
]

[DOCUMENTATION]
ORG_NAME="AuxanoAVOX"
ORG_URL="https://github.com/AuxanoAVOX"
ORG_DESCRIPTION="Auxano ecosystem assets and Stellar Classic wrapper metadata."

[[CURRENCIES]]
code="WAVXO"
issuer="GB4E45WIBUGCFXL6TTAOZU5L2FGH4VIM3KD2PYMPKAQN45QPBLBQZBCZ"
display_decimals=7
name="Wrapped Auxano"
desc="WAVXO is the Stellar Classic wrapped representation of AVXO (Soroban)."
image="https://github.com/AuxanoAVOX/wrapped-auxano-wavxo/blob/main/assets/WAVXO.png"
status="live"
is_asset_anchored=false
anchor_asset_type="crypto"
